# Reto - Deserción de Empleados

## Importa las librerías requeridas.

In [1]:
import pandas as pd
import numpy as np

## Lee el archivo CSV llamado empleadosRETO.csv y coloca los datos en un frame de Pandas llamado EmpleadosAttrition.

In [2]:
EmpleadosAttrition = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/DataSets/empleadosRETO.csv")

EmpleadosAttrition.head()

,Age,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,...,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsInCurrentRole,YearsSinceLastPromotion,Attrition
0,50,Travel_Rarely,Research & Development,1 km,2,Medical,1,997,4,Male,...,22,4,3,80,32,1,2,4,1,No
1,36,Travel_Rarely,Research & Development,6 km,2,Medical,1,178,2,Male,...,20,4,4,80,7,0,3,2,0,No
2,21,Travel_Rarely,Sales,7 km,1,Marketing,1,1780,2,Male,...,13,3,2,80,1,3,3,0,1,Yes
3,52,Travel_Rarely,Research & Development,7 km,4,Life Sciences,1,1118,2,Male,...,19,3,4,80,18,4,3,6,4,No
4,33,Travel_Rarely,Research & Development,15 km,1,Medical,1,582,2,Male,...,12,3,4,80,15,2,4,6,7,Yes

In [3]:
EmpleadosAttrition.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 30 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       400 non-null    int64
 1   BusinessTravel            396 non-null    object
 2   Department                400 non-null    object
 3   DistanceFromHome          400 non-null    object
 4   Education                 400 non-null    int64
 5   EducationField            400 non-null    object
 6   EmployeeCount             400 non-null    int64
 7   EmployeeNumber            400 non-null    int64
 8   EnvironmentSatisfaction   400 non-null    int64
 9   Gender                    400 non-null    object
 10  JobInvolvement            400 non-null    int64
 11  JobLevel                  400 non-null    int64
 12  JobRole                   400 non-null    object
 13  JobSatisfaction           400 non-null    int64
 14  MaritalStatus             395 non-null    object
 15  MonthlyIncome             400 non-null    int64
 16  NumCompaniesWorked        400 non-null    int64
 17  HiringDate                400 non-null    object
 18  Over18                    400 non-null    object
 19  OverTime                  400 non-null    object
 20  PercentSalaryHike         400 non-null    int64
 21  PerformanceRating         400 non-null    int64
 22  RelationshipSatisfaction  400 non-null    int64
 23  StandardHours             400 non-null    int64
 24  TotalWorkingYears         400 non-null    int64
 25  TrainingTimesLastYear     400 non-null    int64
 26  WorkLifeBalance           400 non-null    int64
 27  YearsInCurrentRole        400 non-null    int64
 28  YearsSinceLastPromotion   400 non-null    int64
 29  Attrition                 400 non-null    object
dtypes: int64(19), object(11)
memory usage: 93.9+ KB

## Elimina las columnas que, con alta probabilidad (estimada por ti), no tienen relación alguna con la salida. Hay algunas columnas que contienen información que no ayuda a definir el desgaste de un empleado, tal es caso de las siguientes:

### EmployeeCount: número de empleados, todos tienen un 1

### EmployeeNumber: ID del empleado, el cual es único para cada empleado

### Over18: mayores de edad, todos dicen “Y”

### StandardHours: horas de trabajo, todos tienen “80”

In [4]:
EmpleadosAttrition = EmpleadosAttrition.drop(["EmployeeCount", "EmployeeNumber", "Over18", "StandardHours"], axis=1)

In [5]:
EmpleadosAttrition.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 26 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       400 non-null    int64
 1   BusinessTravel            396 non-null    object
 2   Department                400 non-null    object
 3   DistanceFromHome          400 non-null    object
 4   Education                 400 non-null    int64
 5   EducationField            400 non-null    object
 6   EnvironmentSatisfaction   400 non-null    int64
 7   Gender                    400 non-null    object
 8   JobInvolvement            400 non-null    int64
 9   JobLevel                  400 non-null    int64
 10  JobRole                   400 non-null    object
 11  JobSatisfaction           400 non-null    int64
 12  MaritalStatus             395 non-null    object
 13  MonthlyIncome             400 non-null    int64
 14  NumCompaniesWorked        400 non-null    int64
 15  HiringDate                400 non-null    object
 16  OverTime                  400 non-null    object
 17  PercentSalaryHike         400 non-null    int64
 18  PerformanceRating         400 non-null    int64
 19  RelationshipSatisfaction  400 non-null    int64
 20  TotalWorkingYears         400 non-null    int64
 21  TrainingTimesLastYear     400 non-null    int64
 22  WorkLifeBalance           400 non-null    int64
 23  YearsInCurrentRole        400 non-null    int64
 24  YearsSinceLastPromotion   400 non-null    int64
 25  Attrition                 400 non-null    object
dtypes: int64(16), object(10)
memory usage: 81.4+ KB

## Analiza la información proporcionada, si detectaste que no se cuenta con los años que el empelado lleva en la compañía y parece ser un buen dato. Dicha cantidad se puede calcular con la fecha de contratación ‘HiringDate’.

## Crea una columna llamada Year y obtén el año de contratación del empleado a partir de su fecha ‘HiringDate’. No se te olvide que debe ser un entero.

In [6]:
EmpleadosAttrition["Year"] = EmpleadosAttrition["HiringDate"].str[-4:].astype(int)

## Crea una columna llamada YearsAtCompany que contenga los años que el empleado lleva en la compañía hasta el año 2018. Para su cálculo, usa la variable Year que acabas de crear.

In [7]:
EmpleadosAttrition["YearsAtCompany"] = 2018 - EmpleadosAttrition["Year"]

In [8]:
EmpleadosAttrition[["HiringDate", "Year", "YearsAtCompany"]].head()

   HiringDate  Year  YearsAtCompany
0  06/06/2013  2013               5
1  12/25/2015  2015               3
2   2/14/2017  2017               1
3   7/29/2010  2010               8
4  10/07/2011  2011               7

## La DistanceFromHome está dada en kilómetros, pero tiene las letras “km” al final y así no puede ser entera.

## Renombra la variable DistanceFromHome a DistanceFromHome_km.

In [9]:
EmpleadosAttrition.rename(columns={"DistanceFromHome":"DistanceFromHome_km"}, inplace=True)

In [10]:
EmpleadosAttrition.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 28 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       400 non-null    int64
 1   BusinessTravel            396 non-null    object
 2   Department                400 non-null    object
 3   DistanceFromHome_km       400 non-null    object
 4   Education                 400 non-null    int64
 5   EducationField            400 non-null    object
 6   EnvironmentSatisfaction   400 non-null    int64
 7   Gender                    400 non-null    object
 8   JobInvolvement            400 non-null    int64
 9   JobLevel                  400 non-null    int64
 10  JobRole                   400 non-null    object
 11  JobSatisfaction           400 non-null    int64
 12  MaritalStatus             395 non-null    object
 13  MonthlyIncome             400 non-null    int64
 14  NumCompaniesWorked        400 non-null    int64
 15  HiringDate                400 non-null    object
 16  OverTime                  400 non-null    object
 17  PercentSalaryHike         400 non-null    int64
 18  PerformanceRating         400 non-null    int64
 19  RelationshipSatisfaction  400 non-null    int64
 20  TotalWorkingYears         400 non-null    int64
 21  TrainingTimesLastYear     400 non-null    int64
 22  WorkLifeBalance           400 non-null    int64
 23  YearsInCurrentRole        400 non-null    int64
 24  YearsSinceLastPromotion   400 non-null    int64
 25  Attrition                 400 non-null    object
 26  Year                      400 non-null    int64
 27  YearsAtCompany            400 non-null    int64
dtypes: int64(18), object(10)
memory usage: 87.6+ KB

## Crea una nueva variable DistanceFromHome que sea entera, es decir, solo con números.

In [11]:
EmpleadosAttrition["DistanceFromHome"] = EmpleadosAttrition["DistanceFromHome_km"].str[:-3].astype(int)

In [12]:
EmpleadosAttrition[["DistanceFromHome","DistanceFromHome_km"]].head(10)

   DistanceFromHome DistanceFromHome_km
0                 1                1 km
1                 6                6 km
2                 7                7 km
3                 7                7 km
4                15               15 km
5                 4                4 km
6                 1                1 km
7                16               16 km
8                 4                4 km
9                 2                2 km

## Borra las columnas Year, HiringDate y DistanceFromHome_km debido a que ya no son útiles.

In [13]:
EmpleadosAttrition = EmpleadosAttrition.drop(["Year","HiringDate","DistanceFromHome_km"],axis=1)

In [14]:
EmpleadosAttrition.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 26 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       400 non-null    int64
 1   BusinessTravel            396 non-null    object
 2   Department                400 non-null    object
 3   Education                 400 non-null    int64
 4   EducationField            400 non-null    object
 5   EnvironmentSatisfaction   400 non-null    int64
 6   Gender                    400 non-null    object
 7   JobInvolvement            400 non-null    int64
 8   JobLevel                  400 non-null    int64
 9   JobRole                   400 non-null    object
 10  JobSatisfaction           400 non-null    int64
 11  MaritalStatus             395 non-null    object
 12  MonthlyIncome             400 non-null    int64
 13  NumCompaniesWorked        400 non-null    int64
 14  OverTime                  400 non-null    object
 15  PercentSalaryHike         400 non-null    int64
 16  PerformanceRating         400 non-null    int64
 17  RelationshipSatisfaction  400 non-null    int64
 18  TotalWorkingYears         400 non-null    int64
 19  TrainingTimesLastYear     400 non-null    int64
 20  WorkLifeBalance           400 non-null    int64
 21  YearsInCurrentRole        400 non-null    int64
 22  YearsSinceLastPromotion   400 non-null    int64
 23  Attrition                 400 non-null    object
 24  YearsAtCompany            400 non-null    int64
 25  DistanceFromHome          400 non-null    int64
dtypes: int64(18), object(8)
memory usage: 81.4+ KB

## Aprovechando los ajustes que se están haciendo, la empresa desea saber si todos los departamentos tienen un ingreso promedio similar. Genera una nuevo frame llamado SueldoPromedioDepto que contenga el MonthlyIncome promedio por departamento de los empleados y colócalo en una variable llamada SueldoPromedio. Esta tabla solo es informativa, no la vas a utilizar en el set de datos que estás construyendo.

In [15]:
SueldoPromedioDepto = EmpleadosAttrition[["Department","MonthlyIncome"]].groupby("Department").mean()

SueldoPromedioDepto

                        MonthlyIncome
Department
Human Resources           6239.888889
Research & Development    6804.149813
Sales                     7188.250000

## La variable MonthlyIncome tiene un valor numérico muy grande comparada con las otras variables. Escala dicha variable para que tenga un valor entre 0 y 1.

Se usará Min-Max

In [16]:
EmpleadosAttrition["MonthlyIncome_escalada"] = (EmpleadosAttrition["MonthlyIncome"] - EmpleadosAttrition["MonthlyIncome"].min())/(EmpleadosAttrition["MonthlyIncome"].max() - EmpleadosAttrition["MonthlyIncome"].min())

EmpleadosAttrition.drop("MonthlyIncome", axis=1, inplace=True)

EmpleadosAttrition.rename(columns={"MonthlyIncome_escalada":"MonthlyIncome"},inplace=True)

EmpleadosAttrition.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 26 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       400 non-null    int64
 1   BusinessTravel            396 non-null    object
 2   Department                400 non-null    object
 3   Education                 400 non-null    int64
 4   EducationField            400 non-null    object
 5   EnvironmentSatisfaction   400 non-null    int64
 6   Gender                    400 non-null    object
 7   JobInvolvement            400 non-null    int64
 8   JobLevel                  400 non-null    int64
 9   JobRole                   400 non-null    object
 10  JobSatisfaction           400 non-null    int64
 11  MaritalStatus             395 non-null    object
 12  NumCompaniesWorked        400 non-null    int64
 13  OverTime                  400 non-null    object
 14  PercentSalaryHike         400 non-null    int64
 15  PerformanceRating         400 non-null    int64
 16  RelationshipSatisfaction  400 non-null    int64
 17  TotalWorkingYears         400 non-null    int64
 18  TrainingTimesLastYear     400 non-null    int64
 19  WorkLifeBalance           400 non-null    int64
 20  YearsInCurrentRole        400 non-null    int64
 21  YearsSinceLastPromotion   400 non-null    int64
 22  Attrition                 400 non-null    object
 23  YearsAtCompany            400 non-null    int64
 24  DistanceFromHome          400 non-null    int64
 25  MonthlyIncome             400 non-null    float64
dtypes: float64(1), int64(17), object(8)
memory usage: 81.4+ KB

## Todo parece indicar que las variables categóricas que quedan sí son importantes para obtener la variable de salida. Convierte todas las variables categóricas que quedan a numéricas:
a) BusinessTravel

b) Department

c) EducationField

d) Gender

e) JobRole

f) MaritalStatus

g) Attrition

In [ ]:
def cat_a_num(serie, df):
  df_temporal = pd.get_dummies(df[serie], prefix=serie)
  df = pd.concat([df,df_temporal], axis=1)
  df.drop(serie,axis=1, inplace=True)
  return df

EmpleadosAttrition = cat_a_num("BusinessTravel", EmpleadosAttrition)
EmpleadosAttrition = cat_a_num("Department", EmpleadosAttrition)
EmpleadosAttrition = cat_a_num("EducationField", EmpleadosAttrition)
EmpleadosAttrition = cat_a_num("Gender", EmpleadosAttrition)
EmpleadosAttrition = cat_a_num("JobRole", EmpleadosAttrition)
EmpleadosAttrition = cat_a_num("MaritalStatus", EmpleadosAttrition)
EmpleadosAttrition = cat_a_num("Attrition", EmpleadosAttrition)

In [19]:
EmpleadosAttrition.loc[EmpleadosAttrition["Attrition"]=="Yes","Attrition"] = 1
EmpleadosAttrition.loc[EmpleadosAttrition["Attrition"]=="No","Attrition"] = 0

In [29]:
EmpleadosAttrition["Attrition"] = EmpleadosAttrition["Attrition"].astype(int)

In [26]:
EmpleadosAttrition.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 46 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Age                                400 non-null    int64
 1   Education                          400 non-null    int64
 2   EnvironmentSatisfaction            400 non-null    int64
 3   JobInvolvement                     400 non-null    int64
 4   JobLevel                           400 non-null    int64
 5   JobSatisfaction                    400 non-null    int64
 6   NumCompaniesWorked                 400 non-null    int64
 7   OverTime                           400 non-null    object
 8   PercentSalaryHike                  400 non-null    int64
 9   PerformanceRating                  400 non-null    int64
 10  RelationshipSatisfaction           400 non-null    int64
 11  TotalWorkingYears                  400 non-null    int64
 12  TrainingTimesLastYear              400 non-null    int64
 13  WorkLifeBalance                    400 non-null    int64
 14  YearsInCurrentRole                 400 non-null    int64
 15  YearsSinceLastPromotion            400 non-null    int64
 16  Attrition                          400 non-null    object
 17  YearsAtCompany                     400 non-null    int64
 18  DistanceFromHome                   400 non-null    int64
 19  MonthlyIncome                      400 non-null    float64
 20  BusinessTravel_Non-Travel          400 non-null    uint8
 21  BusinessTravel_Travel_Frequently   400 non-null    uint8
 22  BusinessTravel_Travel_Rarely       400 non-null    uint8
 23  Department_Human Resources         400 non-null    uint8
 24  Department_Research & Development  400 non-null    uint8
 25  Department_Sales                   400 non-null    uint8
 26  EducationField_Human Resources     400 non-null    uint8
 27  EducationField_Life Sciences       400 non-null    uint8
 28  EducationField_Marketing           400 non-null    uint8
 29  EducationField_Medical             400 non-null    uint8
 30  EducationField_Other               400 non-null    uint8
 31  EducationField_Technical Degree    400 non-null    uint8
 32  Gender_Female                      400 non-null    uint8
 33  Gender_Male                        400 non-null    uint8
 34  JobRole_Healthcare Representative  400 non-null    uint8
 35  JobRole_Human Resources            400 non-null    uint8
 36  JobRole_Laboratory Technician      400 non-null    uint8
 37  JobRole_Manager                    400 non-null    uint8
 38  JobRole_Manufacturing Director     400 non-null    uint8
 39  JobRole_Research Director          400 non-null    uint8
 40  JobRole_Research Scientist         400 non-null    uint8
 41  JobRole_Sales Executive            400 non-null    uint8
 42  JobRole_Sales Representative       400 non-null    uint8
 43  MaritalStatus_Divorced             400 non-null    uint8
 44  MaritalStatus_Married              400 non-null    uint8
 45  MaritalStatus_Single               400 non-null    uint8
dtypes: float64(1), int64(17), object(2), uint8(26)
memory usage: 72.8+ KB

## 14. Ahora debes hacer la evaluación de las variables para quedarte con las mejores. Calcula la correlación lineal de cada una de las variables con respecto al Attrition.

In [32]:
correlacion = EmpleadosAttrition.corr()["Attrition"]

<ipython-input-32-12df5c81035f>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  correlacion = EmpleadosAttrition.corr()["Attrition"]

In [66]:
correlacion

Age                                 -0.212121
Education                           -0.055531
EnvironmentSatisfaction             -0.124327
JobInvolvement                      -0.166785
JobLevel                            -0.214266
JobSatisfaction                     -0.164957
NumCompaniesWorked                  -0.009082
PercentSalaryHike                   -0.060880
PerformanceRating                   -0.006471
RelationshipSatisfaction            -0.030945
TotalWorkingYears                   -0.213329
TrainingTimesLastYear               -0.070884
WorkLifeBalance                     -0.021723
YearsInCurrentRole                  -0.203918
YearsSinceLastPromotion             -0.069000
Attrition                            1.000000
YearsAtCompany                      -0.176001
DistanceFromHome                     0.052732
MonthlyIncome                       -0.194936
BusinessTravel_Non-Travel           -0.100698
BusinessTravel_Travel_Frequently     0.035387
BusinessTravel_Travel_Rarely         0.042755
Department_Human Resources           0.023389
Department_Research & Development   -0.072269
Department_Sales                     0.066116
EducationField_Human Resources       0.043404
EducationField_Life Sciences        -0.027457
EducationField_Marketing             0.016768
EducationField_Medical              -0.054144
EducationField_Other                -0.004275
EducationField_Technical Degree      0.129104
Gender_Female                        0.028839
Gender_Male                         -0.028839
JobRole_Healthcare Representative   -0.103274
JobRole_Human Resources              0.032714
JobRole_Laboratory Technician        0.125264
JobRole_Manager                     -0.089885
JobRole_Manufacturing Director      -0.042404
JobRole_Research Director           -0.116263
JobRole_Research Scientist           0.007977
JobRole_Sales Executive             -0.003115
JobRole_Sales Representative         0.191294
MaritalStatus_Divorced              -0.107869
MaritalStatus_Married               -0.094734
MaritalStatus_Single                 0.205849
Name: Attrition, dtype: float64

## 15. Selecciona solo aquellas variables que tengan una correlación mayor o igual a 0.1, dejándolas en otro frame llamado EmpleadosAttritionFinal. No olvides mantener la variable de salidaAttrition; esto es equivalente a borrar las que no cumplen con el límite.

In [40]:
EmpleadosAttritionFinal = EmpleadosAttrition[correlacion[correlacion.abs()>0.1].index]

EmpleadosAttritionFinal

,Age,EnvironmentSatisfaction,JobInvolvement,JobLevel,JobSatisfaction,TotalWorkingYears,YearsInCurrentRole,Attrition,YearsAtCompany,MonthlyIncome,BusinessTravel_Non-Travel,EducationField_Technical Degree,JobRole_Healthcare Representative,JobRole_Laboratory Technician,JobRole_Research Director,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Single
0,50,4,3,4,4,32,4,0,5,0.864269,0,0,0,0,1,0,1,0
1,36,2,3,2,2,7,2,0,3,0.207340,0,0,0,0,0,0,1,0
2,21,2,3,1,2,1,0,1,1,0.088062,0,0,0,0,0,1,0,1
3,52,2,3,3,2,18,6,0,8,0.497574,0,0,1,0,0,0,0,1
4,33,2,3,3,3,15,6,1,7,0.664470,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,33,3,3,1,4,8,4,1,5,0.075248,0,0,0,1,0,0,0,0
396,31,2,1,2,3,4,2,1,2,0.187197,0,0,0,0,0,0,0,0
397,37,2,3,3,4,10,8,0,10,0.589327,0,0,0,0,1,0,1,0
398,38,4,3,1,3,7,0,0,0,0.121124,0,0,0,1,0,0,0,0
399,33,4,3,1,2,8,7,0,8,0.092122,0,0,0,0,0,0,0,0

## 16. Crea una nueva variable llamada EmpleadosAttritionPCA formada por los componentes principales del frame EmpleadosAttritionFinal. Recuerda que el resultado del proceso PCA es un numpy array, por lo que, para hacer referencia a una columna, por ejemplo, la 0, puedes usar la instrucción EmpleadosAttritionPCA[:,0]).

In [42]:
from sklearn.decomposition import PCA

pca = PCA()

EmpleadosAttritionFinal_Xcomponents = EmpleadosAttritionFinal.drop("Attrition", axis=1)

pca.fit(EmpleadosAttritionFinal_Xcomponents)

pca.explained_variance_ratio_

array([6.35132215e-01, 2.41822114e-01, 7.89541075e-02, 2.10427145e-02,
       6.51841699e-03, 6.42036940e-03, 2.98872103e-03, 2.79843370e-03,
       1.32034501e-03, 6.70241444e-04, 6.38779112e-04, 4.67568379e-04,
       4.19324622e-04, 2.84133911e-04, 2.74902956e-04, 2.21740272e-04,
       2.58723157e-05])

In [48]:
EmpleadosAttritionPCA = pca.transform(EmpleadosAttritionFinal_Xcomponents)

EmpleadosAttritionPCA

array([[ 20.25171807,   4.20653731,  10.72200073, ...,  -0.11288255,
         -0.0491599 ,  -0.05235947],
       [ -6.38443246,   3.69113024,  -0.15379179, ...,  -0.04522202,
         -0.0695414 ,   0.05067501],
       [-21.50806343,  -1.74661374,   3.22251706, ...,   0.2752508 ,
          0.54650606,  -0.02230866],
       ...,
       [ -0.64290448,  -3.41880043,  -3.34892641, ...,  -0.30466678,
         -0.04539567,  -0.02191581],
       [ -6.31583751,   7.69763086,   0.86312436, ...,   0.04245991,
          0.06593909,  -0.05130699],
       [ -5.5915908 ,  -3.52757407,  -2.05910088, ...,  -0.19204162,
         -0.08194147,  -0.02258153]])

## 18. Guarda el set de datos que has formado y que tienes en EmpleadosAttritionFinal en un archivo CSV llamado EmpleadosAttritionFinal.csv. Las últimas columnas que colocaste quedarán después de la variable Attrition, lo cual no importa, pero si gustas lo puedes arreglar antes de escribir el archivo.

In [84]:
EmpleadosAttritionFinal = EmpleadosAttritionFinal[['Age', 'EnvironmentSatisfaction', 'JobInvolvement', 'JobLevel',
       'JobSatisfaction', 'TotalWorkingYears', 'YearsInCurrentRole',
       'YearsAtCompany', 'MonthlyIncome',
       'BusinessTravel_Non-Travel', 'EducationField_Technical Degree',
       'JobRole_Healthcare Representative', 'JobRole_Laboratory Technician',
       'JobRole_Research Director', 'JobRole_Sales Representative',
       'MaritalStatus_Divorced', 'MaritalStatus_Single', "Attrition"]]

EmpleadosAttritionFinal.to_csv("/content/drive/MyDrive/Colab Notebooks/DataSets/EmpleadosAttritionFinal.csv")

## 17. Agrega el mínimo número de Componentes Principales en columnas del frame EmpleadosAttritionPCA que logren explicar el 80% de la varianza, al frame EmpleadosAttritionFinal. Puedes usar la instrucción assign, columna por columna, llamando a cada unaC0, C1, etc., hasta las que vayas a agregar.

In [68]:
porcentajes = pca.explained_variance_ratio_.round(3)*100
porcentajes

array([63.5, 24.2,  7.9,  2.1,  0.7,  0.6,  0.3,  0.3,  0.1,  0.1,  0.1,
        0. ,  0. ,  0. ,  0. ,  0. ,  0. ])

In [71]:
contador = 0
variacion = 0

for i in pca.explained_variance_ratio_:
  if variacion >= 0.8:
    break
  variacion += i
  contador += 1

print(contador)

2

De acuerdo a la lista de porcentajes y al código hecho previamente, los primeros dos componentes explican el 80% de la variación de los datos, por lo que solo se usarán las primeras dos columnas

In [88]:
EmpleadosAttritionFinal = EmpleadosAttritionFinal.assign(C0 = EmpleadosAttritionPCA[:,0],
                               C1 = EmpleadosAttritionPCA[:,1])

EmpleadosAttritionFinal[["Attrition", "C0", "C1"]]

     Attrition         C0        C1
0            0  20.251718  4.206537
1            0  -6.384432  3.691130
2            1 -21.508063 -1.746614
3            0  13.825952  5.843352
4            1  -1.426167 -4.145066
..         ...        ...       ...
395          1  -6.969313 -0.384950
396          1 -12.035081  2.043356
397          0  -0.642904 -3.418800
398          0  -6.315838  7.697631
399          0  -5.591591 -3.527574

[400 rows x 3 columns]

## 19. Descarga tu script (archivo con extensión .ipynb) y guárdalo en un archivo que siga la nomenclatura que se te indica en Formato de entrega de actividad.

## 20. Sube el archivo a  Github.  Copia la liga (External lynk)

## 21. Compara tus resultados al descargar rúbrica.pdf.